"""add avatar_url and cover_url to users

Revision ID: 0eb459549cad
Revises: 7cd7952ab78e
Create Date: 2026-05-16 00:17:25.151265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eb459549cad'
down_revision: Union[str, Sequence[str], None] = '7cd7952ab78e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('cover_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cover_url')
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###
