"""add pgvector extension and post embedding column

Revision ID: 6913e43a27a7
Revises: 085dc0ab220c
Create Date: 2026-08-02 02:32:14.447237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '6913e43a27a7'
down_revision: Union[str, Sequence[str], None] = '085dc0ab220c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.add_column('posts', sa.Column('embedding', pgvector.sqlalchemy.Vector(768), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'embedding')
    # ### end Alembic commands ###

